version: '3'
services:
  web:
    build: ./server/
    ports:
      - 3003:3003
    links:
      - db
    depends_on:
      - db
      - tone_service
  tone_service:
    build: ./tone_service/
    ports:
      - 5000:5000
  db:
    image: mongo:4.0.8
    healthcheck:
        test: ["CMD", "curl",  "localhost:9200/_cluster/health?wait_for_status=yellow"]
        start_period: 120s
        timeout: 5s
        interval: 15s
        retries: 5
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017