version: '3'
services:
  web:
    build: ./server/
    ports:
      - 3003:3003
    links:
      - db
      - tone_service
    depends_on:
      - db
      - mongo_seed
      - tone_service
  tone_service:
    build: ./tone_service/
    ports:
      - 5000:5000
  mongo_seed:
    build: ./mongo_seed/
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo:4.0.8
    ports:
      - 27017:27017