# -*- coding: utf-8 -*-
"""toneapp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZVwDxaQ7Gdl0EjRCShnNLHjeR9SCOTOp
"""

from google.colab import drive
drive.mount('/content/drive')

import librosa, librosa.display
import matplotlib.pyplot as plt
import numpy as np
import os

#number of samples per fft
n_fft = 2048
#amount fft is moved in time
hop_length = 512

def create_spectrograms(): 
    os.mkdir("spectrograms")
    for audio_file in os.listdir("/content/drive/My Drive/tone_wav"):
        print(audio_file)
        samples, sample_rate = librosa.load("/content/drive/My Drive/tone_wav/" + audio_file)
        fig = plt.figure(figsize=[0.72,0.72])
        ax = fig.add_subplot(111)
        ax.axes.get_xaxis().set_visible(False)
        ax.axes.get_yaxis().set_visible(False)
        ax.set_frame_on(False)
        filename  = "/content/spectrograms/" + audio_file.replace('.wav','.png')
        S = librosa.feature.melspectrogram(y=samples, sr=sample_rate)
        librosa.display.specshow(librosa.power_to_db(S, ref=np.max))
        plt.savefig(filename, dpi=400, bbox_inches='tight',pad_inches=0)
        plt.close('all')

create_spectrograms()